# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)^(
    src/otherCode/|
    src/echosms/resources/|
    .*\.csv$
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: detect-private-key
    - id: fix-byte-order-marker
    - id: check-added-large-files

  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8 # v2.4.3
    hooks:
      - id: codespell
        args: ["--skip=src/otherCode,*.ipynb,*.pdf,*.svg", "-w", "docs", "src"]

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
    hooks:
      - id: actionlint

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2eeb5678de71a00c0902cbda7105d328432f72cb # v0.16.8
    hooks:
      - id: ruff-check
        args: ["--color", "always"]
      # - id: ruff-format
