[build-system]
requires = ["hatchling", 'hatch-vcs']
build-backend = "hatchling.build"

[project]
name = 'echosms'
import-names = ["echosms"]
license = "MIT"
license-files = ["LICENSE",]
keywords = ["acoustic", "backscatter", "model"]
authors = [
  { name="Mike Jech"},
  { name="Gavin Macaulay"}
]
description = 'Acoustic backscattering models used in aquatic ecosystem research'
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
	"numpy>=2.2.0",
	"scipy>=1.15.0",
	"pandas>=2.3.0",
	"xarray>=2024.10.0",
	"trimesh>=4.4.4",
	"pymeshlab>=2023.12.post2",
	"shapely>=2.0.6",
	"mapbox_earcut>=1.0.2",
	"spheroidalwavefunctions>=0.0.1",
	"tqdm>=4.66.5",
	"mapply>=0.1.27",
	"requests>=2.32.4",
	"rtoml>=0.12.0",
	"urllib3>=1.26.20",
	"matplotlib>=3.10.0",
	"rich>=13.8.0",
	"jsonschema-rs>=0.18.1",
	"orjson>=3.10.7",
	"manifold3d>=3.0.0",
]
classifiers = [
    'Development Status :: 4 - Beta',
    'Environment :: Console',
    'Intended Audience :: Science/Research',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Topic :: Scientific/Engineering',
    'Topic :: Scientific/Engineering :: Physics',
    'Topic :: Scientific/Engineering :: Oceanography',
    'Natural Language :: English',
]
dynamic = [ 'version']

[project.scripts]
echosms-view = "echosms.viewer.app:main"
validate-toml = "echosms.datastore.validate_toml:main"
process-for-datastore = "echosms.datastore.process_for_datastore:main"

[project.urls]
Homepage = 'https://github.com/ices-tools-dev/echoSMs'
Issues = 'https://github.com/ices-tools-dev/echoSMs/issues'
Documentation = 'https://ices-tools-dev.github.io/echoSMs'
Repository = 'https://github.com/ices-tools-dev/echoSMs'

[dependency-groups]
dev = [
    "json-schema-for-humans>=1.5.1",
    "mkdocs>=1.6.1, <2",
    "mkdocs-glightbox>=0.5.2",
    "mkdocs-macros-plugin>=1.5.0",
    "mkdocs-material>=9.7.6, <10",
    "mkdocstrings-python>=2.0.3",
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "pytest-xdist>=3.8.0",
    "ruff>=0.15.22",
    "spyder-kernels>=3.1.4",
    "zensical>=0.0.38",
]

[tool.hatch.version]
source = 'vcs'

[tool.hatch.build.targets.wheel]
packages = ["src/echosms"]

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"  # otherwise the non-tagged version is not accepted by testpypi

[tool.uv]
exclude-newer = "7 days"
exclude-newer-package = { zensical = "1 day" }
audit = {'malware-check' = true}
preview-features = ["audit-command", "malware-check"]  # silences the preview features warnings

[tool.pytest.ini_options]
testpaths = ['tests',]
addopts = ["--import-mode=importlib", "--cov=echosms", "--cov-report=html", "--cov-report=term"]
markers = [
    "internet: tests that require internet access (mostly to the echoSMs datastore)",
]

[tool.coverage.run]
omit = ["src/echosms/viewer/*.py",]
parallel = true

[tool.coverage.report]
show_missing = true
sort = "cover"

[tool.coverage.html]
directory = "coverage_report"

[tool.ruff]
line-length = 100
extend-exclude = ["src/otherCode"]
preview = true

[tool.ruff.lint]
# select = ["E", "W", "F", "S", "D"]
# select = ['ALL']
ignore = [
    "D103", # missing docstring in public function
    "D100", # missing docstring in public module
    "D102", # missing docstring in public method
    "D101", # missing docstring in public class
    "D104", # missing docstring in public package
    "D107", # missing docstring in __init__
    "D203", # blank line before class
    "D213", # mulitline summary second line
    "Q000", # single quotes found but double quotes preferred
    "COM812", # trailing comma missing
    "E226", # missing whitespace around arthmetic operator
    # These are temporary ignores when select = ["ALL"]
    "EM102",
    "FBT001",
    "FBT002",
    "ANN001",
    "ANN201",
    "PLC0415",
    "PT011",
    "I001",
    "N806",
    "N802",
    "T201",
    "CPY001",
    "INP001",
    "EM101",
    "TRY003",
    "ERA001",
    "PLR0912", # too many branches
    "C901", # too complex
    "PLR0917", # too many positional arguments
    "PLR0913", # too many arguments in function definition
    "PLR0915", # too many statements

]

extend-select = [
    "B006",     # do not use mutable structures for argument defaults
    "F",        # Pyflakes rules
    "W",        # PyCodeStyle warnings
    "E",        # PyCodeStyle errors
    "I",        # Sort imports properly
    "UP",       # Warn if certain things can changed due to newer Python versions
    "C4",       # Catch incorrect use of comprehensions, dict, list, etc
    "FA",       # Enforce from __future__ import annotations
    "ISC",      # Good use of string concatenation
    "ICN",      # Use common import conventions
    "RET",      # Good return practices
    "SIM",      # Common simplification rules
    "TID",      # Some good import practices
    "TC",       # Enforce importing certain types in a TYPE_CHECKING block
    "PTH",      # Use pathlib instead of os.path
    "TD",       # Be diligent with TODO comments
    "NPY",      # Some numpy-specific things
    "FURB",     # Suggest more idiomatic Python patterns
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101"] # disables assert warnings in testing
