function fig = config()

grey=[0.75 0.75 0.75];
pos=[0.1 0.1 0.8 0.8];
% 	'FileName=E:\Zooplankton\ZBS\config.m'
h0 = figure('Color',[0.8 0.8 0.8], ...
   'Name','BACKSCATTERING BY ZOOPLANKTON', ...
	'PaperPosition',[18 180 576 432], ...
   'PaperUnits','points', ...
   'Units','normalized', ...
	'Position',pos, ...
	'Tag','Fig1');
%	'ToolBar','none');
% Geometric Shape
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.05 0.5 0.25 0.45], ...
	'Style','frame', ...
	'Tag','FrameShape');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ForegroundColor',[0 0 1], ...
	'ListboxTop',0, ...
	'Position',[0.105    0.93    0.135    0.042], ...
	'String','Shape', ...
	'Style','text', ...
	'Tag','StaticTextShape');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.08 0.895 0.096 0.03], ...
	'String','Length (mm)', ...
	'Style','text', ...
	'Tag','StaticTextLength');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.21 0.90 0.06 0.03], ...
	'String','30', ...
	'Style','edit', ...
	'Tag','EditTextLength');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.08 0.855 0.096 0.03], ...
	'String','rho/L', ...
	'Style','text', ...
	'Tag','StaticTextRho_L');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.21 0.86 0.06 0.03], ...
	'String','3', ...
	'Style','edit', ...
	'Tag','EditTextRho_L');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.08 0.815 0.096 0.03], ...
	'String','L/a', ...
	'Style','text', ...
	'Tag','StaticTextL_a');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.21 0.82 0.06 0.03], ...
	'String','16', ...
	'Style','edit', ...
	'Tag','EditTextL_a');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.08 0.775 0.096 0.03], ...
	'String','Taper order', ...
	'Style','text', ...
	'Tag','StaticTextTaperOrder');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.21 0.78 0.06 0.03], ...
	'String','10', ...
	'Style','edit', ...
	'Tag','EditTextTaperOrder');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'Callback','checkbox_action(1);', ...				
	'ListboxTop',0, ...
	'Position',[0.07022106631989597 0.73 0.14 0.03], ...
	'String','Length Average ', ...
	'Style','checkbox', ...
	'Value',0, ...
	'Tag','CheckboxLengthAve');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.08 0.685 0.096 0.03], ...
	'String','Std(L/<L>)', ...
   'Enable','off', ...
	'Style','text', ...
	'Tag','StaticTextStdL');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.21 0.69 0.06 0.03], ...
	'String','0.1', ...
	'Style','edit', ...
   'Enable','off', ...
	'Tag','EditTextStdL');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.08 0.645 0.096 0.03], ...
	'String','L  increment', ...
	'Style','text', ...
   'Enable','off', ...
	'Tag','StaticTextDL');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.21 0.65 0.06 0.03], ...
	'String','0.01', ...
	'Style','edit', ...
   'Enable','off', ...
	'Tag','EditTextDL');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','checkbox_action(2);', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.07 0.60 0.08 0.03], ...
	'String','Profile', ...
	'Style','checkbox', ...
	'Value',0, ...
	'Tag','CheckboxProfile');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','pushbutton_action(0);', ...
	'ListboxTop',0, ...
	'Position',[0.18  0.60    0.08   0.03], ...
	'String','Browse', ...
   'Enable','off', ...
	'Tag','PushbuttonBrowse');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.06 0.555 0.13 0.03], ...
	'String','Taper Smooth', ...
	'Style','text', ...
   'Enable','off', ...
	'Tag','StaticTextTaperSmooth');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.21 0.56 0.06 0.03], ...
	'String','40', ...
	'Style','edit', ...
   'Enable','off', ...
	'Tag','EditTextTaperSmooth');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.06 0.515 0.116 0.03], ...
	'String','Axis Smooth', ...
	'Style','text', ...
   'Enable','off', ...
	'Tag','StaticTextAxisSmooth');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.21 0.52 0.06 0.03], ...
	'String','10', ...
	'Style','edit', ...
   'Enable','off', ...
	'Tag','EditTextAxisSmooth');

% orientation frame
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.05 0.08 0.28 0.35], ...
	'Style','frame', ...
	'Tag','FrameOrient');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ForegroundColor',[0 0 1], ...
	'ListboxTop',0, ...
	'Position',[0.12 0.41 0.1365 0.042], ...
	'String','Orientation', ...
	'Style','text', ...
	'Tag','StaticTextOrient');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.08 0.375 0.1 0.03], ...
	'String','<Mean theta>', ...
	'Style','text', ...
	'Tag','StaticTextMeanTheta');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.22 0.38 0.06 0.03], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditTextMeanTheta');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.08 0.335 0.1 0.03], ...
	'String','Begin theta (deg)', ...
	'Style','text', ...
	'Tag','StaticTextTheta0');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.22 0.34 0.06 0.03], ...
	'String','-90', ...
	'Style','edit', ...
	'Tag','EditTextTheta0');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.08 0.295 0.1 0.03], ...
	'String','End theta (deg)', ...
	'Style','text', ...
	'Tag','StaticTextTheta1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.22 0.30 0.06 0.03], ...
	'String','270', ...
	'Style','edit', ...
	'Tag','EditTextTheta1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'Callback','checkbox_action(3);', ...
	'ListboxTop',0, ...
	'Position',[0.07 0.25 0.15 0.03], ...
	'String','Orietation Average', ...
	'Style','checkbox', ...
	'Value',0, ...
	'Tag','CheckboxOrientAve');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'Callback','radio_action(1);', ...
	'ListboxTop',0, ...
	'Position',[0.08 0.21 0.11 0.03], ...
	'String','Uniform PDF', ...
	'Style','radiobutton', ...
   'Enable','off', ...
	'Tag','RadiobuttonUniPDF');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'Callback','radio_action(2);', ...
	'ListboxTop',0, ...
	'Position',[0.20 0.21 0.12 0.03], ...
	'String','Gaussian PDF', ...
	'Style','radiobutton', ...
	'Tag','RadiobuttonGaussPDF', ...
   'Enable','off', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.08 0.165 0.12 0.03], ...
	'String','std(theta) (deg)', ...
	'Style','text', ...
   'Enable','off', ...
	'Tag','StaticTextStdTheta');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.22 0.17 0.06 0.03], ...
	'String','20', ...
	'Style','edit', ...
   'Enable','off', ...
	'Tag','EditTextStdTheta');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.08 0.125 0.12 0.03], ...
	'String','Theta increment (deg)', ...
	'Style','text', ...
   'Enable','off', ...
	'Tag','StaticTextDtheta');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.22 0.13 0.06 0.03], ...
	'String','1', ...
	'Style','edit', ...
   'Enable','off', ...
	'Tag','EditTextDtheta');

% Physical properties
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.35 0.11 0.28 0.32], ...
	'Style','frame', ...
	'Tag','FramePhy');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ForegroundColor',[0 0 1], ...
	'ListboxTop',0, ...
	'Position',[0.42 0.41 0.1365 0.042], ...
	'String','Material property', ...
	'Style','text', ...
	'Tag','StaticTextPhy');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[0.38 0.375 0.15 0.03], ...
	'String','Density contrast (g)', ...
	'Style','text', ...
	'Tag','StaticTextg');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.54 0.38 0.06 0.03], ...
	'String','1.0357', ...
	'Style','edit', ...
	'Tag','EditTextg');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.36 0.335 0.17 0.03], ...
	'String','Sound speed contrast (h)', ...
	'Style','text', ...
	'Tag','StaticTexth');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.54 0.34 0.06 0.03], ...
	'String','1.0279', ...
	'Style','edit', ...
	'Tag','EditTexth');
 h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'Callback','checkbox_action(4);', ...
	'ListboxTop',0, ...
	'Position',[0.38 0.29 0.14 0.03], ...
	'String','Inhomogenous body', ...
	'Style','checkbox', ...
	'Value',0, ...
   'Tag','CheckboxInhomo');

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[0.37  0.245 0.16 0.03], ...
	'String',' No. of body segments', ...
	'Style','text', ...
   'Enable','off', ...
	'Tag','StaticTextSegment');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.54 0.25 0.06 0.03], ...
	'String','7', ...
	'Style','edit', ...
   'Enable','off', ...
	'Tag','EditTextSegment');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[0.45 0.205 0.08 0.03], ...
	'String',' std(g)', ...
	'Style','text', ...
   'Enable','off', ...
	'Tag','StaticTextStdg');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.54 0.21 0.06 0.03 ], ...
	'String','0.0016', ...
	'Style','edit', ...
   'Enable','off', ...
	'Tag','EditTextStdg');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[0.45 0.165 0.08 0.03], ...
	'String',' std(h)', ...
	'Style','text', ...
   'Enable','off', ...
	'Tag','StaticTextStdh');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.54 0.17 0.06 0.03 ], ...
	'String','0.0015', ...
	'Style','edit', ...
   'Enable','off', ...
	'Tag','EditTextStdh');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[0.36 0.125 0.17 0.03], ...
	'String',' Correlation Length (% of L)', ...
	'Style','text', ...
   'Enable','off', ...
	'Tag','StaticTextCorrL');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.54 0.13 0.06 0.03 ], ...
	'String','20', ...
	'Style','edit', ...
   'Enable','off', ...
	'Tag','EditTextCorrL');

% Simulation
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.65 0.11 0.30 0.32], ...
	'Style','frame', ...
	'Tag','FrameSimu');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ForegroundColor',[0 0 1], ...
	'ListboxTop',0, ...
	'Position',[0.73 0.41 0.1365 0.042], ...
	'String','Simulation', ...
	'Style','text', ...
	'Tag','StaticTextSimu');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.69 0.38 0.08 0.03], ...
	'String',' Output', ...
	'Style','text', ...
	'Tag','StaticTextOutput');
Str1={'Scat. ampl.','Cross section','TS','RTS'};
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.67 0.35 0.1 0.03], ...
	'String',Str1, ...
	'Style','popupmenu', ...
	'Tag','PopupMenuOutput', ...
	'Value',3);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.775 0.34 0.03 0.03], ...
	'String',' VS', ...
   'Fontsize',6, ...
	'Style','text', ...
	'Tag','StaticTextVs');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.84 0.38 0.08 0.03], ...
	'String','Variable', ...
	'Style','text', ...
	'Tag','StaticTextVar');
Str2={' Frequency (kHz)','angle (deg)','ka'};
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
   'Callback','popupmenu_action(1);',...
	'ListboxTop',0, ...
	'Position',[0.81 0.35 0.11 0.03], ...
	'String',Str2, ...
	'Style','popupmenu', ...
	'Tag','PopupMenuVar', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[0.67 0.295 0.11 0.03], ...
	'String',' Sample points', ...
	'Style','text', ...
	'Tag','StaticTextNpts');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.84 0.30 0.06 0.03], ...
	'String','100', ...
	'Style','edit', ...
	'Tag','EditTextNpts');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[0.67 0.255 0.11 0.03], ...
	'String',' Integration points', ...
	'Style','text', ...
	'Tag','StaticTextNint');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.84 0.26 0.06 0.03], ...
	'String','2000', ...
	'Style','edit', ...
	'Tag','EditTextNint');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[0.67 0.215 0.13 0.03], ...
	'String',' Variable start value', ...
	'Style','text', ...
	'Tag','StaticTextVar0');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.84 0.22 0.06 0.03], ...
	'String','15', ...
	'Style','edit', ...
	'Tag','EditTextVar0');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.67 0.175 0.13 0.03], ...
	'String',' Variable end value', ...
	'Style','text', ...
	'Tag','StaticTextVar1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.84 0.18 0.06 0.030], ...
	'String','600', ...
	'Style','edit', ...
	'Tag','EditTextVar1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.67 0.135 0.13 0.03], ...
	'String','Frequency (kHz)', ...
	'Style','text', ...
	'Enable','off', ...
	'Tag','StaticTextFreq');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[0.84 0.14 0.06 0.030], ...
	'String','120', ...
	'Style','edit', ...
	'Enable','off', ...
	'Tag','EditTextFreq');

% graphic window

clr_order=[        0         0    1.0000
         0    0.5000         0
    1.0000         0         0
         0    0.7500    0.7500
    0.7500         0    0.7500
    0.7500    0.7500         0
    0.2500    0.2500    0.2500];
h1 = axes('Parent',h0, ...
	'Units','normalized', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',clr_order, ...
	'Position',[0.4 0.55 0.5 0.4], ...
	'Tag','AxesFig1', ...
	'XColor',[0 0 0], ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.498812351543943 -0.125 9.160254037844386], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.08313539192399044 0.4955357142857144 9.160254037844386], ...
	'Rotation',90, ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.8741092636579573 1.25 9.160254037844386], ...
	'Tag','Axes1Text2', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[0.498812351543943 1.035714285714286 9.160254037844386], ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);

% Push Button Commands
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'Callback','pushbutton_action(1);', ...
	'ListboxTop',0, ...
	'Position',[0.36 0.03 0.11 0.05], ...
	'String','Load Config', ...
	'Tag','PushButtonLoadConfig');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'Callback','pushbutton_action(2);', ...
	'ListboxTop',0, ...
	'Position',[0.48 0.03 0.11 0.05], ...
	'String','Save Config', ...
	'Tag','PushButtonSaveConfig');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'Callback','pushbutton_action(3);', ...
	'ListboxTop',0, ...
	'Position',[0.60 0.03 0.08 0.05], ...
	'String','Save ', ...
	'Tag','PushButtonSave');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'Callback','pushbutton_action(4);', ...
	'ListboxTop',0, ...
	'Position',[0.69  0.03  0.08  0.05], ...
	'String','Start', ...
	'Tag','PushButtonStart');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'Callback','pushbutton_action(5);', ...
	'ListboxTop',0, ...
	'Position',[0.78 0.03 0.08 0.05], ...
	'String','Stop', ...
	'Tag','PushButtonStop');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'Callback','close', ...
	'ListboxTop',0, ...
	'Position',[0.87 0.03 0.08 0.05], ...
	'String','Quit', ...
	'Tag','PushButtonQuit');
if nargout > 0, fig = h0; end
