function fig = gh_figure()
global para  status

grey=[0.75 0.75 0.75];
white=[1.0 1.0 1.0];
pos=[0.14 0.13 0.8 0.8];
h0_1=findobj('Tag','Fig1');
h2=findobj(h0_1(1),'Tag','EditTextNint');
para.simu.ni=str2num(get(h2,'string'));
status.save=0;

h0 = figure('Color',[0.8 0.8 0.8], ...
   'Name','GENERATE INHOMOGENOUS MATERIAL PROPERTY PROFILES (g and h)', ...
	'PaperPosition',[18 180 576 432], ...
   'PaperUnits','points', ...
   'Units','normalized', ...
	'Position',pos, ...
	'Tag','Fig2');
%	'ToolBar','none');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.25 0.45 0.15 0.03], ...
	'String','Specified Parameters', ...
	'Style','text', ...
	'Tag','StaticTextTitle1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.45 0.45 0.15 0.03], ...
	'String','Constructed Parameters', ...
	'Style','text', ...
   'Tag','StaticTextTitle2');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.1 0.40 0.1 0.03], ...
	'String','No. of Seg.', ...
	'Style','text', ...
   'Tag','StaticText2SegNo');
h2=findobj(h0_1,'Tag','EditTextSegment');
Varstr=get(h2,'String');
para.phy.seg_no=str2num(Varstr);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',white, ...
	'ListboxTop',0, ...
	'Position',[0.275 0.40 0.1 0.03], ...
	'String',Varstr, ...
	'Style','edit', ...
   'Tag','EditText2SegNo1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',white, ...
	'ListboxTop',0, ...
	'Position',[0.475 0.40 0.1 0.03], ...
	'String',' ', ...
	'Style','edit', ...
   'Tag','EditText2SegNo2');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.1 0.35 0.1 0.03], ...
	'String','<g>', ...
	'Style','text', ...
   'Tag','StaticText2Meang');
h2=findobj(h0_1,'Tag','EditTextg');
Varstr=get(h2,'String');
para.phy.g0=str2num(Varstr);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',white, ...
	'ListboxTop',0, ...
	'Position',[0.275 0.35 0.1 0.03], ...
	'String',Varstr, ...
	'Style','edit', ...
   'Tag','EditText2Meang1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',white, ...
	'ListboxTop',0, ...
	'Position',[0.475 0.35 0.1 0.03], ...
	'String',' ', ...
	'Style','edit', ...
   'Tag','EditText2Meang2');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.1 0.30 0.1 0.03], ...
	'String','<h>', ...
	'Style','text', ...
   'Tag','StaticText2Meanh');
h2=findobj(h0_1,'Tag','EditTexth');
Varstr=get(h2,'String');
para.phy.h0=str2num(Varstr);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',white, ...
	'ListboxTop',0, ...
	'Position',[0.275 0.30 0.1 0.03], ...
	'String',Varstr, ...
	'Style','edit', ...
   'Tag','EditText2Meanh1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',white, ...
	'ListboxTop',0, ...
	'Position',[0.475 0.30 0.1 0.03], ...
	'String',' ', ...
	'Style','edit', ...
   'Tag','EditText2Meanh2');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.1 0.25 0.1 0.03], ...
	'String','std(g)', ...
	'Style','text', ...
   'Tag','StaticText2Stdg');
h2=findobj(h0_1,'Tag','EditTextStdg');
Varstr=get(h2,'String');
para.phy.g_std=str2num(Varstr);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',white, ...
	'ListboxTop',0, ...
	'Position',[0.275 0.25 0.1 0.03], ...
	'String',Varstr, ...
	'Style','edit', ...
   'Tag','EditText2Stdg1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',white, ...
	'ListboxTop',0, ...
	'Position',[0.475 0.25 0.1 0.03], ...
	'String',' ', ...
	'Style','edit', ...
   'Tag','EditText2Stdg2');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.1 0.20 0.1 0.03], ...
	'String','std(h)', ...
	'Style','text', ...
   'Tag','StaticText2Stdh');
h2=findobj(h0_1,'Tag','EditTextStdh');
Varstr=get(h2,'String');
para.phy.h_std=str2num(Varstr);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',white, ...
	'ListboxTop',0, ...
	'Position',[0.275 0.20 0.1 0.03], ...
	'String',Varstr, ...
	'Style','edit', ...
   'Tag','EditText2Stdh1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',white, ...
	'ListboxTop',0, ...
	'Position',[0.475 0.20 0.1 0.03], ...
	'String',' ', ...
	'Style','edit', ...
   'Tag','EditText2Stdh2');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.08 0.15 0.12 0.03], ...
	'String','Corrlation Length', ...
	'Style','text', ...
   'Tag','StaticText2CorrL1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'ListboxTop',0, ...
	'Position',[0.08 0.12 0.12 0.03], ...
	'String','(% of body Length)', ...
	'Style','text', ...
   'Tag','StaticText2CorrL2');
h2=findobj(h0_1,'Tag','EditTextCorrL');
Varstr=get(h2,'String');
para.phy.corrL=str2num(Varstr);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',white, ...
	'ListboxTop',0, ...
	'Position',[0.275 0.15 0.1 0.03], ...
	'String',Varstr, ...
	'Style','edit', ...
   'Tag','EditText2CorrL1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',white, ...
	'ListboxTop',0, ...
	'Position',[0.475 0.15 0.1 0.03], ...
	'String',' ', ...
	'Style','edit', ...
   'Tag','EditText2CorrL2');

% graphic window
subplot(221)
subplot(222)

% Push Button Commands
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'Callback','pushbutton2_action(1);', ...
	'ListboxTop',0, ...
	'Position',[0.36 0.03 0.11 0.05], ...
	'String','Load Profile', ...
	'Tag','PushButtonLoadProfile');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'Callback','pushbutton2_action(2);', ...
	'ListboxTop',0, ...
	'Position',[0.48 0.03 0.11 0.05], ...
	'String','Save Profile', ...
	'Tag','PushButtonSaveProfile');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'Callback','pushbutton2_action(3);', ...
	'ListboxTop',0, ...
	'Position',[0.60  0.03  0.08  0.05], ...
	'String','Start', ...
	'Tag','PushButtonStart');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'Callback','pushbutton2_action(4);', ...
	'ListboxTop',0, ...
	'Position',[0.69 0.03 0.11 0.05], ...
	'String','Done', ...
	'Tag','PushButtonSaveQuit');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',grey, ...
	'Callback','close', ...
	'ListboxTop',0, ...
	'Position',[0.81 0.03 0.08 0.05], ...
	'String','Cancel', ...
	'Tag','PushButtonQuit');
if nargout > 0, fig = h0; end
