name: Update dependency versions to meet SPEC 0

on:
  schedule:
    # Day 3 of each quarter. Allows one day buffer after the quarterly schedule release on day 1
    - cron: "24 1 3 1,4,7,10 *"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update:
    permissions:
      contents: write # this actions pushes commits so needs write permission
      pull-requests: write # this action creates a pull request if dependency versions need updating
    name: update dependency minimum versions
    runs-on: ubuntu-latest
    steps:
      - uses: scientific-python/spec0-action@7c875bc60508e9aab2bdb851e99bfcc53b283e94 # v1.6
        with:
          update_all: 2 # also bump non-SPEC0 deps older than 2 years
          pr_title: "SPEC0: Drop support for older versions of dependencies"
          commit_msg: "Drop support for older versions of dependencies (as per SPEC 0)"
